### ISSUE TITLE
Cant run solution

### ISSUE THREAD

**Issue by Lachlann** [macdonaldfin/HotelsAPIDemo#1]
Hey Findlay
Thanks for completing this code test, we are just trying to run it but we cant get it to work as it appears there is no startup or Program.cs files commited. Could you take a look ?

**Comment by macdonaldfin** [comment]
Hi,

Apologies, they seemed to have been excluded from the batch upload!
I've uploaded them to the /HotelsAPI/ folder now.

Please let me know if you have any further issues.

Thanks.

Kind regards, Findlay.

**Comment by macdonaldfin** [comment]
Additionally, I've patched the HotelsController file in the HotelsAPI/Controllers/ as one of the end points contained a typo.
